imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    httpProtocol: "%dev_protocol%"
    recaptcha: true
    analytics: true

framework:
    #esi:             ~
    #translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        enable_analytics: "%analytics%"
        google_analytics: "%google.analytics%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        logging: false
        profiling: false
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: tls
    port: 587
    auth_mode:  login
    spool:     { type: memory }

#Gedmo extensions
stof_doctrine_extensions:
    default_locale: en_us
    translation_fallback: true
    orm:
        default:
            timestampable: true

#FOSUserBundle
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: VoteBundle\Entity\User
    registration:
        confirmation:
            enabled:    true # disabled during development
    from_email:
        address:        noreply@peopledecide.org
        sender_name:    People Decide
    service:
        mailer: vote.email

monolog:
  handlers:
    app_stream:
      type:  stream
      level: info
      path:  %kernel.logs_dir%/%kernel.environment%_app.log
      channels: app
    debug_stream:
      type:  stream
      level: debug
      path:  %kernel.logs_dir%/%kernel.environment%_debug.log
      channels: app
    php_stream:
      type:  stream
      level: error
      path:  %kernel.logs_dir%/%kernel.environment%_php.log
      channels: php

assetic:
    assets:
        stylesheets:
            inputs:
                - '@VoteBundle/Resources/css/main.css'
        core:
            inputs:
                - '@VoteBundle/Resources/js/core.js'
        address_autocomplete:
            inputs:
                - '@VoteBundle/Resources/js/address_autocomplete.js'
        vote:
            inputs:
                - '@VoteBundle/Resources/js/vote.js'