# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_VOLUNTEER:   ROLE_USER
        ROLE_CANDIDATE:   ROLE_VOLUNTEER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                default_target_path: /
            logout:
                path:                 /logout
            anonymous:    true
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|img|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

    access_control:

        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%httpProtocol%" }
        - { path: ^/css, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%httpProtocol%" }
        - { path: ^/img, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%httpProtocol%" }
        - { path: ^/js, role: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: "%httpProtocol%" }

        - { path: ^/admin/, role: ROLE_ADMIN, requires_channel: %httpProtocol% }
