# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    core_exception_listener:
        class: VoteBundle\Listener\CoreExceptionListener
        arguments: ["@kernel", "@logger", "@router", "@twig", "@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: app }

    vote.option:
        class: VoteBundle\Service\OptionService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]
    vote.user:
        class: VoteBundle\Service\UserService
        arguments: ["@doctrine.orm.entity_manager", "@vote.option", "@validator"]
    vote.email:
        class: VoteBundle\Service\EmailService
        arguments: ["@service_container"]
    vote.document:
        class: VoteBundle\Service\DocumentService
        arguments: ["@doctrine.orm.entity_manager"]
    vote.js:
        class: VoteBundle\Service\JSService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]
    vote.nationbuilder:
        class: VoteBundle\Service\NationBuilderService
        arguments: ["@service_container", "%nationbuilder.baseURL%", "%nationbuilder.clientID%", "%nationbuilder.secret%", "%nationbuilder.testToken%"]
    vote.pdf:
        class: VoteBundle\Service\PDFService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]
    vote.electoral_roll:
        class: VoteBundle\Service\ElectoralRollService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]
