# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    core_exception_listener:
        class: VoteBundle\Listener\CoreExceptionListener
        arguments: ["@logger", "@router", "@twig", "@session"]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }
            - { name: monolog.logger, channel: app }

    vote.option:
        class: VoteBundle\Service\OptionService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]
    vote.pdf:
        class: VoteBundle\Service\PDFService
        arguments: ["@doctrine.orm.entity_manager", "@service_container", "@logger"]
